import { prisma } from "@/lib/prisma";
import { SubscriptionTier } from "@prisma/client";

export interface PlanConfig {
  id: SubscriptionTier;
  name: string;
  tagline: string;
  monthlyPrice: number; // in INR
  annualPrice: number; // in INR
  monthlyPaise: number;
  annualPaise: number;
  invoiceLimitPerMonth: number | null; // null = unlimited
  userLimit: number | null; // null = unlimited
  features: {
    name: string;
    included: boolean;
  }[];
}

export const SUBSCRIPTION_PLANS: Record<SubscriptionTier, PlanConfig> = {
  FREE: {
    id: "FREE",
    name: "Starter Free",
    tagline: "Ideal for small independent retail shops & start-ups",
    monthlyPrice: 0,
    annualPrice: 0,
    monthlyPaise: 0,
    annualPaise: 0,
    invoiceLimitPerMonth: 100,
    userLimit: 1,
    features: [
      { name: "Up to 100 GST Invoices per month", included: true },
      { name: "POS Thermal & A4 Invoice Printing", included: true },
      { name: "Customer Khata (Credit Ledger)", included: true },
      { name: "Basic Inventory Tracking", included: true },
      { name: "1 Staff / Owner User", included: true },
      { name: "AI Purchase Bill Scanner", included: false },
      { name: "NIC E-Way Bill JSON Generation", included: false },
      { name: "Excel / CSV Bulk Inventory Import", included: false },
      { name: "Print Configuration Studio & Themes", included: false },
      { name: "MCA Electronic Audit Trail Logs", included: false },
    ],
  },
  PRO: {
    id: "PRO",
    name: "SmartVyapar Pro",
    tagline: "For growing businesses needing automation & compliance",
    monthlyPrice: 499,
    annualPrice: 4999,
    monthlyPaise: 49900,
    annualPaise: 499900,
    invoiceLimitPerMonth: null, // Unlimited
    userLimit: null, // Unlimited
    features: [
      { name: "Unlimited GST Invoices & Bills", included: true },
      { name: "Unlimited Multi-User Team & Roles", included: true },
      { name: "AI Purchase Bill Scanner (Gemini OCR)", included: true },
      { name: "NIC E-Way Bill JSON Bulk Generator", included: true },
      { name: "RFC 4180 Excel / CSV Bulk Inventory Engine", included: true },
      { name: "Print Studio: 7 Color Palettes & Custom Logos", included: true },
      { name: "Automobile Job Cards & Restaurant KOT", included: true },
      { name: "GSTR-1 Portal JSON & GSTR-3B Summary", included: true },
      { name: "Statutory MCA Electronic Audit Trail", included: true },
      { name: "WhatsApp 1-Click Bill Sharing", included: true },
    ],
  },
  ENTERPRISE: {
    id: "ENTERPRISE",
    name: "Enterprise Multi-Branch",
    tagline: "For large dealerships, chains & multi-outlet retailers",
    monthlyPrice: 1999,
    annualPrice: 19999,
    monthlyPaise: 199900,
    annualPaise: 1999900,
    invoiceLimitPerMonth: null,
    userLimit: null,
    features: [
      { name: "Everything in Pro Tier", included: true },
      { name: "Multi-Store Centralized Inventory Sync", included: true },
      { name: "Dedicated Database Instance", included: true },
      { name: "Custom API & Hardware Webhooks", included: true },
      { name: "Priority 24x7 Dedicated Account Manager", included: true },
    ],
  },
};

/**
 * Calculates invoices generated by the tenant in the current calendar month
 */
export async function getTenantMonthlyInvoiceCount(tenantId: string): Promise<number> {
  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);

  return await prisma.invoice.count({
    where: {
      tenantId,
      createdAt: {
        gte: startOfMonth,
      },
    },
  });
}

/**
 * Calculates active staff/team members registered under this tenant
 */
export async function getTenantUserCount(tenantId: string): Promise<number> {
  return await prisma.user.count({
    where: {
      tenantId,
      isActive: true,
    },
  });
}

/**
 * Returns comprehensive subscription, usage, and quota status for a tenant
 */
export async function getTenantSubscriptionDetails(tenantId: string) {
  const tenant = await prisma.tenant.findUnique({
    where: { id: tenantId },
    select: {
      id: true,
      businessName: true,
      subscriptionTier: true,
      subscriptionStatus: true,
      planBillingCycle: true,
      planExpiresAt: true,
      subscriptionPayments: {
        orderBy: { createdAt: "desc" },
        take: 10,
      },
    },
  });

  if (!tenant) {
    throw new Error("Tenant not found");
  }

  const tier = tenant.subscriptionTier as SubscriptionTier;
  const plan = SUBSCRIPTION_PLANS[tier] || SUBSCRIPTION_PLANS.FREE;

  const [monthlyInvoices, userCount] = await Promise.all([
    getTenantMonthlyInvoiceCount(tenantId),
    getTenantUserCount(tenantId),
  ]);

  const isExpired =
    tenant.planExpiresAt && new Date() > tenant.planExpiresAt && tier !== "FREE";

  const effectiveTier = isExpired ? "FREE" : tier;

  return {
    tier: effectiveTier,
    rawTier: tier,
    isExpired,
    status: tenant.subscriptionStatus,
    billingCycle: tenant.planBillingCycle,
    expiresAt: tenant.planExpiresAt,
    planDetails: SUBSCRIPTION_PLANS[effectiveTier],
    usage: {
      monthlyInvoices,
      invoiceLimit: plan.invoiceLimitPerMonth,
      isInvoiceLimitReached:
        plan.invoiceLimitPerMonth !== null && monthlyInvoices >= plan.invoiceLimitPerMonth,
      userCount,
      userLimit: plan.userLimit,
      isUserLimitReached: plan.userLimit !== null && userCount >= plan.userLimit,
    },
    payments: tenant.subscriptionPayments,
  };
}
